# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9958e49fd29ece4754cd3491bf70de534b6d32bb683c79c9f342349884b39c46abfdeaa6c96cdd24a2983701c7fe72ae7096ee7e8cfc10db63f238b1be7d8ef

test:
  secret_key_base: 50df53190a57a474e4afc0ffd09f17d8bea831f585351778679eee204365cb4efd575f628492c33b89e48bacd399dfbe8d5500e9e670837a4e66fd504a1790c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
